/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { Dex } from "./Dex";
export type { IERC20 } from "./IERC20";
export * as factories from "./factories";
export { Dex__factory } from "./factories/Dex__factory";
export { IERC20__factory } from "./factories/IERC20__factory";
