# 配置参考 https://segmentfault.com/a/1190000020340570
version: '3'
services:

  # 后端服务
  service-park:
    container_name: service-park-view
    image: ${DOCKER_IMAGE_TAG}
    restart: always
    networks:
      - park-network
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.service-park-view.entrypoints=websecure"
      - "traefik.http.routers.service-park-view.rule=Host(`park.matrix-net.tech`)"
      - "traefik.http.routers.service-park-view.tls.certresolver=aliyunresolver"
      - "traefik.http.services.service-park-view.loadbalancer.server.port=3000"

networks:
  park-network:
    driver: bridge
    name: park-network
