/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as cryptoMarketSol from "./CryptoMarket.sol";
export type { cryptoMarketSol };
import type * as dexSol from "./Dex.sol";
export type { dexSol };
